// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10cKaHnvywBJBWdILWXFv7xWI3oywbjg',
    appId: '1:965812952660:web:b74959ef4590dc6e6f57c1',
    messagingSenderId: '965812952660',
    projectId: 'mandacakes-8d75d',
    authDomain: 'mandacakes-8d75d.firebaseapp.com',
    storageBucket: 'mandacakes-8d75d.appspot.com',
    measurementId: 'G-B82PDFYQ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTcLml5wOxL5V7diC-G4SLaTvTBviXi0',
    appId: '1:965812952660:android:fe2075c307422ffc6f57c1',
    messagingSenderId: '965812952660',
    projectId: 'mandacakes-8d75d',
    storageBucket: 'mandacakes-8d75d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRBPTHXQKQXVKFQle24tmvCHIlSk3IBY',
    appId: '1:965812952660:ios:7c951ed9ea7c378e6f57c1',
    messagingSenderId: '965812952660',
    projectId: 'mandacakes-8d75d',
    storageBucket: 'mandacakes-8d75d.appspot.com',
    androidClientId: '965812952660-7rj05k8tpri0dc0f7tk49k5e6ne7gas0.apps.googleusercontent.com',
    iosClientId: '965812952660-tf29577tqrk8ro8pbvrev0p15ed9304i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandaCakes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRBPTHXQKQXVKFQle24tmvCHIlSk3IBY',
    appId: '1:965812952660:ios:7c951ed9ea7c378e6f57c1',
    messagingSenderId: '965812952660',
    projectId: 'mandacakes-8d75d',
    storageBucket: 'mandacakes-8d75d.appspot.com',
    androidClientId: '965812952660-7rj05k8tpri0dc0f7tk49k5e6ne7gas0.apps.googleusercontent.com',
    iosClientId: '965812952660-tf29577tqrk8ro8pbvrev0p15ed9304i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandaCakes',
  );
}
